# Generated by Django 5.0.6 on 2024-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='userfiles',
            field=models.ManyToManyField(blank=True, related_name='users_files', related_query_name='user', through='drive.UserFile', to='drive.file'),
        ),
        migrations.AddField(
            model_name='user',
            name='usergroups',
            field=models.ManyToManyField(blank=True, related_name='users_groups', related_query_name='user', through='drive.UserGroup', to='drive.group'),
        ),
    ]
